BUILD_MODE="single"        # all | single
SINGLE_MODEL="K900"

BUILD_NO_LIMITS="yes"  # compile aussi _no_limits
PREFIX_RFP="yes"       # préfixe RFP_
FW_NAME_SUFFIX="RFP-Performance"   # "" = désactivé
